version: "3"

services:
  test-everything:
    image: californiasvaluedtrust/php:${PHP_IMAGE}
    depends_on:
      - composer-install
      - sql-server
    volumes:
      - ./:/app
    command: vendor/bin/phpunit --verbose

  test-sql-server:
    image: californiasvaluedtrust/php:${PHP_IMAGE}
    depends_on:
      - composer-install
      - sql-server
    volumes:
    - ./:/app
    command: vendor/bin/phpunit --verbose --group=SqlServer

  composer-install:
    image: californiasvaluedtrust/php:${PHP_IMAGE}
    volumes:
    - ./:/var/www
    command: tail -f /dev/null

  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports:
    - 11433:1433
    environment:
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
      - MSSQL_DATABASE=${MSSQL_DATABASE}
      - SA_PASSWORD=${MSSQL_PASSWORD}
